"""
Django settings for grassland project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import configparser
from grassland.settings.settings import *
GEOSERVER_URL = "http://localhost:8080"
R_PATH = "C://Program Files/R/R-4.1.2/bin/x64/R.exe"
if parser.has_section("captcha_google") and parser.has_section("postgresql"):
    params = parser.items("captcha_google")
    GOOGLE_RECAPTCHA_SECRET_KEY = params[0][1]
    params = parser.items("postgresql_local")
    db_name = params[1][1]
    db_user = params[2][1]
    db_pass = params[3][1]
    db_host = params[0][1]
    # db_port = params[4][1]
else:
    raise Exception(
        'Section {0} not found in the {1} file'.format("captcha_google", filename))

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_pass,
        'HOST': db_host,
        # 'PORT': db_port
    }
}