"""
Django settings for grassland project.
Generated by 'django-admin startproject' using Django 3.1.5.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import configparser
from grassland.settings.settings import *

DEBUG = True
# GEOSERVER_URL = "https://geoserver:8443/geoserver/"
# production server is "http://grazescape:8080"
#GEOSERVER_URL = "http://grazescape:8080"
GEOSERVER_URL = "http://geoserver:8080"
R_PATH = "/opt/conda/envs/gscape/bin/R"
# get section, default to postgresql
db = {}
params = ""
db_name = ""
db_user = ""
db_pass = ""
db_host = ""
db_port = ""
if parser.has_section("captcha_google") and parser.has_section("postgresql"):
    params = parser.items("captcha_google")
    GOOGLE_RECAPTCHA_SECRET_KEY = params[0][1]
    params = parser.items("postgresql")
    db_name = params[1][1]
    db_user = params[2][1]
    db_pass = params[3][1]
    db_host = params[0][1]
    #db_port = params[4][1]
else:
    raise Exception(
        'Section {0} not found in the {1} file'.format("captcha_google", filename))

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_pass,
        'HOST': db_host,
        # 'PORT': db_port
    }
}
