# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/src/osgeo4w/src/qgis/qgis/python/console/console_history_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryDialogPythonConsole(object):
    def setupUi(self, HistoryDialogPythonConsole):
        HistoryDialogPythonConsole.setObjectName("HistoryDialogPythonConsole")
        HistoryDialogPythonConsole.resize(587, 375)
        HistoryDialogPythonConsole.setWindowTitle("Dialog")
        self.gridLayout = QtWidgets.QGridLayout(HistoryDialogPythonConsole)
        self.gridLayout.setContentsMargins(2, 4, 2, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.reloadHistory = QtWidgets.QPushButton(HistoryDialogPythonConsole)
        self.reloadHistory.setAutoDefault(False)
        self.reloadHistory.setObjectName("reloadHistory")
        self.gridLayout.addWidget(self.reloadHistory, 1, 0, 1, 1)
        self.saveHistory = QtWidgets.QPushButton(HistoryDialogPythonConsole)
        self.saveHistory.setEnabled(True)
        self.saveHistory.setAutoDefault(False)
        self.saveHistory.setObjectName("saveHistory")
        self.gridLayout.addWidget(self.saveHistory, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runHistoryButton = QtWidgets.QPushButton(HistoryDialogPythonConsole)
        self.runHistoryButton.setAutoDefault(False)
        self.runHistoryButton.setDefault(True)
        self.runHistoryButton.setObjectName("runHistoryButton")
        self.horizontalLayout.addWidget(self.runHistoryButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(HistoryDialogPythonConsole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.listView = QtWidgets.QListView(HistoryDialogPythonConsole)
        self.listView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setAlternatingRowColors(True)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 3)

        self.retranslateUi(HistoryDialogPythonConsole)
        self.buttonBox.accepted.connect(HistoryDialogPythonConsole.accept)
        self.buttonBox.rejected.connect(HistoryDialogPythonConsole.reject)
        QtCore.QMetaObject.connectSlotsByName(HistoryDialogPythonConsole)

    def retranslateUi(self, HistoryDialogPythonConsole):
        _translate = QtCore.QCoreApplication.translate
        self.reloadHistory.setText(_translate("HistoryDialogPythonConsole", "Reload"))
        self.saveHistory.setText(_translate("HistoryDialogPythonConsole", "Save"))
        self.runHistoryButton.setText(_translate("HistoryDialogPythonConsole", "Run"))
